### ISSUE TITLE
An idea for a video

### ISSUE THREAD

**Issue by ghost** [itsPeetah/Mobile-FPS-and-TPS-controller-for-Unity#1]
Hi. I have seen your youtube videos and they are really well made, impressive. I was wondering if you ever thought on using a FOSS framework to create your controller and expanding it. 
Jut an idea. 
I think it could be a good idea for your youtube channel: https://github.com/mikhomak/Erbium

**Comment by itsPeetah** [comment]
Hi, first of all, thank you!
Secondly, I am not really familiar with the technique you’re hinting: I thought that posting it here was already making it “open source”. What should I do to implement a FOSS framework?

**Comment by ghost** [comment]
Oh. I didn't explain myself correctly. I mean, instead of making something from zero, you could expand an already made asset, posted here on github. For example, you could take this: https://github.com/dbrizov/NaughtyCharacter and expand it to have melee combat. Just an idea.

**Comment by itsPeetah** [comment]
You are totally right, that sounds like a good video idea. Thank you very much.
The reason I made it from scratch is that I hope people will take away how it works after watching my video, and are not just grabbing the code without learning how it works (and that is way easier for me to do if I have my own code to comment). I will take this idea in consideration though, it can actually save me a lot of time in the future. Thanks again!
